# Generated by Django 3.0.1 on 2021-01-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("content", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=30)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
