# Generated by Django 3.0.1 on 2021-02-09 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_auto_20210128_0049"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["date"]},
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
