# Generated by Django 3.0.1 on 2021-02-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_auto_20210209_1934"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="value",
            new_name="amount",
        ),
    ]
