# Generated by Django 3.0.1 on 2021-03-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0011_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
