# Generated by Django 3.0.1 on 2021-03-30 18:02

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0013_auto_20210322_2032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
